# Site settings
title: Tyler Bugbee
email: tbugbee1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog serves as an ongoing portfolio for my various projects, research interests,
  and academics. Please feel free to contact me directly - email is best.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tylerbugbee.com" # the base hostname & protocol for your site
github_username:  tbarc
linkedin_username: tylerbugbee

# Build settings
markdown: kramdown

sass:
  silence_deprecations:
    - import
    - global-builtin
