# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tyler Bugbee
email: tbugbee1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog serves as an ongoing portfolio for my various projects, research interests,
  and academics. Please feel free to contact me directly - email is best.
baseurl: "home" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  tbarc
twitter_username:  tyler

# Build settings
markdown: kramdown
